### ISSUE TITLE
Confuse on the Reason of Performance Scaling

### ISSUE THREAD

**Issue by yunfan42** [RulinShao/retrieval-scaling#9]
After carefully reading the paper and discussions on OpenReview, I still have some questions I hope the authors can help clarify.

**Preliminary Understanding**

The authors mentioned **Retrieval-Based Language Models during inference**. I would like to confirm my understanding. In the experiment, the process

- Inserting relevant document chunks into the context window of a LLM through dense retrieval
- Directly answering questions by leveraging the In-Context Learning (ICL) capabilities of LLMs
- **Not involving any training or fine-tuning of the LLM itself**

Is this interpretation correct?

### Questions about Scaling Law

I'm somewhat confused by the observation that larger Indexing Datastore consistently improve performance. My specific questions :
Is the performance improvement primarily because:
- Smaller Datastore  lack relevant documents
- Larger  Datastore contain more contextually relevant documents

If this is the case, it seems like an  ”issue of recall“ . Instead of preparing an immensely large indexing datastore, wouldn't it be more effective to prepare multiple, more targeted indexing datastore with hybrid retrieval ?

If my understanding is incorrect, I would greatly appreciate a more detailed explanation from you regarding the reasons behind the performance improvements.

Thank you for your time and insights.

**Comment by RulinShao** [comment]
Hi @yunfan42, thanks for your interest in our work!!! Please find the comments below and let us know if you have further questions!

**RE: Preliminary Understanding**

Yes, your understanding is correct! Our work focuses on datastore scaling, which only adds FLOPS on datastore construction and inference-time FLOPS caused by the extended context length. 

**RE: Questions about Scaling Law**

I fully agree with your point, but that doesn't conflict with our claim. The key question here is how confident you are that all helpful documents have been be included in your datastore. For example, if your application is targeted on a Wikipedia-only QA task, then you should only use the Wikipedia datastore for this particular application. In our case, we are building a general-purpose RAG model that could help improve the LM's performance on both language modeling and several downstream tasks. These tasks, such as MMLU, do not provide an "in-domain datastore". Previous works that use Wikipedia as the datastore showed very limited performance gains on these tasks. Therefore, we constructed a hybrid datastore containing both domain-specific data and general-web data (Table 2) and showed it is helpful for all investigated tasks. The key takeaways are (1) people should consider more and diverse data when constructing a datastore for these open-domain tasks and (2) constructing a large datastore has better compute-optimal scaling curves than training an LM with the same amount of FLOPS. An interesting followup could be investigating effective data selection and processing methods for the datastore to improve its data quality, which is orthogonal to our scaling study. However, we note that adding additional data selection pipeline will only enhance our findings, as you could achieve even higher performance with fewer FLOPS.

I hope these could help address your questions! Thanks for the insightful comments :)

**Comment by yunfan42** [comment]
Thank you for your detailed and insightful response. Your explanation has greatly clarified my understanding of the research paper. I appreciate the time you took to provide such a comprehensive explanation.🙏
